#!/usr/bin/env bash
# Lumen Dark Pool - Day 3 negative-case demo.
#
# Reuses the valid proof + public_inputs generated by scripts/match_proof.sh
# and tampers ONE public input at a time (by XOR-ing the last byte of that
# 32-byte Field). Calls prove_identity against the deployed verifier with
# tampered public_inputs + the ORIGINAL proof. Each tampering must revert
# on-chain.
#
# Layout of public_inputs (224 bytes total, 7 Fields x 32 bytes, big-endian):
#   offset  0..32   Field 0: commit_buy
#   offset 32..64   Field 1: commit_sell
#   offset 64..96   Field 2: nullifier_buy
#   offset 96..128  Field 3: nullifier_sell
#   offset 128..160 Field 4: pair_id
#   offset 160..192 Field 5: fill_amount
#   offset 192..224 Field 6: clearing_price
#
# We tamper only the four Fields whose constraint actually checks them against
# the proof's internal computations (C1 commits, C5 price, C6 fill, C7 nullifier).
# pair_id (Field 4) is NOT validated against the proof (C3 only checks the
# two PRIVATE pair_ids against each other; public pair_id is informational).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# --- Toolchain ----------------------------------------------------------------
: "${PATH:="$HOME/.local/bin:$HOME/.bb/bin:$HOME/.nargo/bin:$HOME/.cargo/bin:$PATH"}"
export PATH
for bin in stellar xxd; do
  command -v "$bin" >/dev/null 2>&1 || { echo "missing: $bin" >&2; exit 1; }
done

STELLAR_NETWORK="${STELLAR_NETWORK:-testnet}"
STELLAR_SOURCE_ACCOUNT="${STELLAR_SOURCE_ACCOUNT:-alice}"
TARGET_DIR="$ROOT/circuits/match/target"
CONTRACT_ID_FILE="$ROOT/.match_verifier_contract_id"

[[ -f "$TARGET_DIR/public_inputs" ]] || { echo "missing $TARGET_DIR/public_inputs; run scripts/match_proof.sh first" >&2; exit 1; }
[[ -f "$TARGET_DIR/proof" ]]             || { echo "missing $TARGET_DIR/proof; run scripts/match_proof.sh first" >&2; exit 1; }
[[ -f "$CONTRACT_ID_FILE" ]]              || { echo "missing $CONTRACT_ID_FILE; run scripts/match_proof.sh first" >&2; exit 1; }

CONTRACT_ID="$(cat "$CONTRACT_ID_FILE")"
echo "reusing verifier $CONTRACT_ID from $CONTRACT_ID_FILE"
echo

# Helper: tamper byte at offset `byte_off` (0-indexed within public_inputs)
# in a copy of public_inputs and invoke prove_identity. Asserts the call
# reverts (non-zero exit code).
try_tamper() {
  local label="$1"
  local byte_off="$2"
  local tmp
  tmp="$(mktemp)"
  cp "$TARGET_DIR/public_inputs" "$tmp"
  # XOR the last byte of the targeted 32-byte Field with 0x01 to flip
  # the lowest bit of the BN254 scalar value. This is enough to make
  # the matching constraint fire.
  local last
  last=$(( byte_off + 32 - 1 ))
  printf '\x01' | dd of="$tmp" bs=1 seek="$last" count=1 conv=notrunc 2>/dev/null

  set +e
  stellar contract invoke \
    --id "$CONTRACT_ID" \
    --source "$STELLAR_SOURCE_ACCOUNT" \
    --network "$STELLAR_NETWORK" \
    --send yes \
    -- \
    prove_identity \
    --public_inputs-file-path "$tmp" \
    --proof_bytes-file-path    "$TARGET_DIR/proof" \
    >/dev/null 2>&1
  local rc=$?
  set -e
  rm -f "$tmp"

  if [[ "$rc" -eq 0 ]]; then
    echo "  FAIL  $label  (verifier accepted tampered input; rc=$rc)"
    return 1
  else
    echo "  OK    $label  (verifier reverted; rc=$rc)"
    return 0
  fi
}

# Field offsets in the public_inputs blob
OFF_COMMIT_BUY=0
OFF_NULL_BUY=64
OFF_FILL=160
OFF_PRICE=192

PASS=0
FAIL=0
echo "== negative-case suite (each must revert on-chain) =================="
try_tamper "tamper commit_buy      (fires C1)"  "$OFF_COMMIT_BUY" && PASS=$((PASS+1)) || FAIL=$((FAIL+1))
try_tamper "tamper nullifier_buy  (fires C7)"  "$OFF_NULL_BUY"  && PASS=$((PASS+1)) || FAIL=$((FAIL+1))
try_tamper "tamper fill_amount    (fires C6)"  "$OFF_FILL"      && PASS=$((PASS+1)) || FAIL=$((FAIL+1))
try_tamper "tamper clearing_price (fires C5)"  "$OFF_PRICE"     && PASS=$((PASS+1)) || FAIL=$((FAIL+1))

echo
echo "RESULT: $PASS passed, $FAIL failed"
[[ "$FAIL" -eq 0 ]] || exit 1
